### ISSUE TITLE
Iframe jitsi does not open the room after clicking Go

### ISSUE THREAD

**Issue by venimus** [aeternity/jitsi-meet#110]
![image](https://user-images.githubusercontent.com/632282/88037083-201e5300-cb4d-11ea-946e-f355e4968ba9.png)
The URL changes but it does not forward to the jitsi server

**Comment by shapkarin** [comment]
@venimus it's closed with https://github.com/aeternity/superhero-ui/pull/722 ?

**Comment by venimus** [comment]
yes
