### ISSUE TITLE
Make Meet share link to use the parent url

### ISSUE THREAD

**Issue by venimus** [aeternity/jitsi-meet#111]
![image](https://user-images.githubusercontent.com/632282/88049913-94adbd80-cb5e-11ea-8c45-7302f5e3184e.png)

in this case to be "superhero.com/meet/Roomname" (or whatever the domain is)

**Comment by venimus** [comment]
![image](https://user-images.githubusercontent.com/632282/89540904-596de880-d806-11ea-8ce6-885b43f122b8.png)

**Comment by shapkarin** [comment]
This feature does not works at Firefox incognito mode. Related PR https://github.com/aeternity/jitsi-meet/pull/162
```
2020-08-18T19:37:07.437Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: TypeError: uri is undefined Script: https://localhost:8080/libs/app.bundle.min.js?v=4358 Line: 383838 Column: 3 StackTrace:  TypeError: uri is undefined
    getDecodedURI uri.js:602
    render CopyMeetingUrl.js:159
    React 10
Logger.js:154:22
Uncaught TypeError: uri is undefined
    getDecodedURI uri.js:602
    render CopyMeetingUrl.js:159
    React 10
uri.js:602:4
```

**Comment by shapkarin** [comment]
I think that it's because `getCurrentConferenceUrl` returns undefined
https://github.com/aeternity/jitsi-meet/blob/075de8dec090bec0b04196cef86320cf31f25171/react/features/base/connection/functions.js#L7-L29

**Comment by shapkarin** [comment]
in some reason `document.referrer` at firefox is a protocol and domain name without path but with slash at the end and next this condition, makes it `undefined`

https://github.com/aeternity/jitsi-meet/blob/075de8dec090bec0b04196cef86320cf31f25171/react/features/base/connection/functions.js#L23-L26

blocks: https://github.com/aeternity/jitsi-meet/pull/187/files

**Comment by shapkarin** [comment]
@Chima1707 https://support.mozilla.org/en-US/questions/1067835

**Comment by venimus** [comment]
done
