### ISSUE TITLE
Avataars

### ISSUE THREAD

**Issue by mradkov** [aeternity/jitsi-meet#112]
We need to use the same avatars as in the superhero-wallet and superhero-ui.

Avatars in superhero and superhero-wallet are using the `avataars` npm package (https://github.com/aeternity/superhero-ui/blob/develop/package.json#L21-L22) with the following config: https://github.com/aeternity/superhero-ui/blob/develop/src/utils/util.js#L46-L66

We need to use the same one for generated avatars in jitsi instead of the robot one.

**Comment by DeeJayElly** [comment]
@mradkov - Do we need to use same avatars like superhero-ui or do we need to generate them in a same way like its implemented there?

**Comment by mradkov** [comment]
> @mradkov - Do we need to use same avatars like superhero-ui or do we need to generate them in a same way like its implemented there?

For the first version of this - let us generate them the same way. Afterward, we can sync them to also display the custom user-uploaded ones.
