### ISSUE TITLE
"Login with web wallet" shouldn't redirect to web wallet if wallet available as extension or in parent frames

### ISSUE THREAD

**Issue by davidyuk** [aeternity/jitsi-meet#122]
Today I have faced this on https://develop.aggregator.z52da5wt.xyz/meet

![Wire 2020-07-23 at 5_00 PM](https://user-images.githubusercontent.com/9007851/88261006-d5e1d100-cd08-11ea-8b00-bf8eb884c840.png)

The Superhero extension was initialized and able to sign JWT challenge. After pressing "Login with web wallet" I have been redirected to web wallet:

![Wire 2020-07-23 at 5_10 PM](https://user-images.githubusercontent.com/9007851/88261152-16d9e580-cd09-11ea-90a7-4b7bb1f085e7.png)

To fix this, I'm proposing
- to run aepp wallet detector (from sdk) right after page loads
- when the user clicks "Login with web wallet":
  - use wallet if wallet detector found one
  - redirect to web wallet otherwise

**Comment by shapkarin** [comment]
> to run aepp wallet detector (from sdk) right after page loads

already implemented in first version

I just hide that button at all if wallet was found. Please check the commit above.

**Comment by davidyuk** [comment]
On tip_button.test.league.aeternity.org button seems disappeared, but I can't check it for sure because I don't have moderator rights
