### ISSUE TITLE
Login with web wallet not working

### ISSUE THREAD

**Issue by venimus** [aeternity/jitsi-meet#127]
There is some weird redirection happening making the user to confirm 2 times the jwt token and end up without login.
to reproduce:
1. Open a room, do not authenticate with extension
2. Click Settings -> Profile -> Login with web wallet
3. Confirm the jwt token
After that you get redirected again in the web wallet

In addition "cancel" does not work redirecting to the same page

**Comment by shapkarin** [comment]
todo: notice, please check the `tip-button` button branch. it includes some fixed about JWT.

**Comment by shapkarin** [comment]
`cancel` is not working (wrong x-cancel param value).
todo: check the server - returns 404

**Comment by venimus** [comment]
when all dialogs are confirmed the user end up disconnected
