### ISSUE TITLE
Freeze the tip button and show success message while the tipping process is going on.

### ISSUE THREAD

**Issue by Chima1707** [aeternity/jitsi-meet#155]

**Comment by shapkarin** [comment]
@Chima1707 maybe show the preloader?

**Comment by venimus** [comment]
How about have that tip form to hide when you click Tip (submit button)
then after a while the success/error messages appear as new popup with the result.

**Comment by shapkarin** [comment]
Why not. It’s easy to achieve.

**Comment by shapkarin** [comment]
But wait. I thinks that some preloading is less confusing.

**Comment by venimus** [comment]
> But wait. I thinks that some preloading is less confusing.

but it might take a while to get the result and would be good to be able to close it before that. Like want to continue watching (the ui blocks the video) or want to tip several users one after other. 
But i agree the original issue description and a loading indicator is at least the minimum to be implemented

**Comment by shapkarin** [comment]
@mike-gusev-ae thanks for the PRs. I think we need disable as it and also maybe also show the preloader or hide that popup.

**Comment by shapkarin** [comment]
I mean place some preloader inside the tooltip.

**Comment by shapkarin** [comment]
@DeeJayElly can you help us to decide?

**Comment by mike-gusev-ae** [comment]
Agree with preloader
