### ISSUE TITLE
Wallet detector was not find a wallet in parent if wallet is an iframe

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#168]
For example when the app is running in Firefox 79.0 inside the iframe at superhero-ui there is one issue and one feature request:
1. There is no popup with conformation. Fix that and make sure that sdk wallet detector works with parent(superhero-ui) in the same way as with the extension.
3. Add jitsi domains to the white list to enable the login without the confirmation.

**Comment by shapkarin** [comment]
Currently that appears at superhero-ui `develop` branch. But works fine without iframe.
also check the https://github.com/aeternity/superhero-ui/pull/719

**Comment by mradkov** [comment]
> Currently that appears at superhero-ui `develop` branch. But works fine without iframe.
> also check the [aeternity/superhero-ui#719](https://github.com/aeternity/superhero-ui/pull/719)

Did you find out what the problem was? Any development on this issue?

**Comment by shapkarin** [comment]
In progress, reading SDK docs and compare `aepp-governance` client and detector with the `jitsi` integration. Hope today will understand how to solve that. Maybe I just missed some SDK features.

**Comment by shapkarin** [comment]
> 2. Add jitsi domains to the white list to enable the login without the confirmation.

https://github.com/aeternity/superhero-wallet/blob/8474261531de7b7f64d4bb689ce3a15f8c34f4fc/src/popup/utils/constants.js#L102-L108

**Comment by shapkarin** [comment]
the main goal is to find a wallet in the parent domain if wallet is an iframe in the parent DOM.
