### ISSUE TITLE
Can't change my name manually after chain name or ak_address was setted

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#172]
- Open for example https://tip_button.test.league.aeternity.org/someRoomName939485
- Set manually some chain name
- reload the page or open other room
- user is not able to change manually "username" to some other, can change only with JWT

**Comment by shapkarin** [comment]
@Chima1707 I can have a look. Or you maybe. I have to solve this one asap https://github.com/aeternity/jitsi-meet/issues/168 for the new superhero-ui release.

**Comment by shapkarin** [comment]
I agreed with @venimus
> may be we simply remove the disable logic, or add a "x" button to clear the input

**Comment by mradkov** [comment]
Users should not be able to change their names if they are logged in with their superhero identity. 

Otherwise, some might pretend to be somebody else. Also somehow we should distinguish users which are logged via the wallet and use their `ak_...` or `.chain` names and those who just simply put that as their display name.

**Comment by shapkarin** [comment]
Thanks, got that. 
> and those who just simply put that as their display name.

true

**Comment by shapkarin** [comment]
> Also somehow we should distinguish users which are logged via the wallet and use their ak_... or .chain names and those who just simply put that as their display name.

We can open a new issue about that

**Comment by venimus** [comment]
So we have to check if the user used the wallet or typed the address manually

**Comment by shapkarin** [comment]
if user use manual name so he can change it next? Maybe we also can make that for prejoin screen, if the name was extracted from JWT we need to disable that or make `X` button as a log-out button that also remove all JWT info from the redux `features/base/jwt`. Also as I understand we can add something like: read only user data if there is JWT used

**Comment by shapkarin** [comment]
Maybe we can just checked JWT redux state 'features/base/jwt'.jwt instead of the name validation or make 'features/base/jwt'.isGuest works. Not actually sure why just dispatch('setJWT') doesn't affects the `isGuest` value.
