### ISSUE TITLE
Don't allow to change user data if JWT was used

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#176]
ref: https://github.com/aeternity/jitsi-meet/issues/172#issuecomment-672690342

If user is logged in with JWT we need to prevent user data manual change from the conference(after prejoin) until user will not log out.

**Comment by mradkov** [comment]
Maybe if something has to be changed - the user should be asked to sign this again. Not sure how applicable this is in jitsi though 🤔 (just thinking out loud)
