### ISSUE TITLE
Add a verified badge to a user if the user .chain name/akAddress is gotten from superhero wallet

### ISSUE THREAD

**Issue by Chima1707** [aeternity/jitsi-meet#178]

**Comment by Chima1707** [comment]
This is quite different from #172

**Comment by mike-gusev-ae** [comment]
I changed avatars logic and now user without wallet, but with ak or .chain name wont have avatar.
But user with wallet and the same name will. So, we dont need bage anymore.

**Comment by mike-gusev-ae** [comment]
Found bug. walletSynced prop is not enough for verifying users, we should use one more parameter.
![Screen Shot 2020-08-13 at 10 28 36](https://user-images.githubusercontent.com/67146735/90106830-a430b880-dd50-11ea-8c7a-23d905736459.png)
