### ISSUE TITLE
If user has chain name use it at prejoin screen as username

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#185]
Use not only ak_adress as a display name

https://github.com/aeternity/jwt-auth/blob/2818bf96da2015c9bdb56f0fdac8f6b732aa62a6/srv/index.js#L72

**Comment by venimus** [comment]
But it appears already working this way. What could be the problem?

**Comment by shapkarin** [comment]
~~@venimus I found what the issue. It's at [jwt-auth repo]( https://github.com/aeternity/jwt-auth/blob/2818bf96da2015c9bdb56f0fdac8f6b732aa62a6/srv/index.js#L72) side. So if user have only one chain name the address will be used.~~

**Comment by shapkarin** [comment]
@venimus I guess that will fix this issue https://github.com/aeternity/jwt-auth/pull/14
