### ISSUE TITLE
Share link bugs

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#207]
- Firefox incognito mode (private move)
- When user user login with deep link the share link is wrong (it use web wallet instead of superhero.com)

**Comment by shapkarin** [comment]
that all because of window referrer
I suggest to use that approach https://github.com/aeternity/jitsi-meet/pull/188

**Comment by venimus** [comment]
i suggest just to make the url put into the configuration
it won't change accross servers anyway

**Comment by shapkarin** [comment]
@venimus suggest to use predefined parent domain name in config. It's much easier way. And we have different configs for the different instances anyway.

**Comment by shapkarin** [comment]
> i suggest just to make the url put into the configuration
> it won't change accross servers anyway

indeed. had some latency and send that message above
