### ISSUE TITLE
"thank you for using SuperheroLeague" should be changed

### ISSUE THREAD

**Issue by ErkanKanden** [aeternity/jitsi-meet#208]
![1](https://user-images.githubusercontent.com/14875828/91427339-082da380-e85e-11ea-8bdb-b10da8cc403e.png)

**Comment by shapkarin** [comment]
@ErkanKanden So we need to change the message to the "Thanks you for using Superhero Meet" if Jitsi is inside an iframe and standalone as well (meet.aepps.com)? Or only when it's inside the Superhero.com?

**Comment by venimus** [comment]
meet.aepps and superhero/meet should be essentially the same service (regardless iframe or not), so text should be the same. I think this can be set in the configuration

**Comment by shapkarin** [comment]
>  I think this can be set in the configuration
Thanks. Yes, it will be nice to have such value in config.

**Comment by venimus** [comment]
I mean this option IS already existing in the config, just need to be setup per server

**Comment by venimus** [comment]
That was fixed in the server config
