### ISSUE TITLE
Login in Brave browser or privat mode

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/jitsi-meet#209]
Hello team! 

I have tested Jitsi Meet in Brave browser. After logging in with the iframe wallet, I entered the meeting room, but the dashboard items are not visible or active (the room is grey).

![Знімок екрана 2020-08-28 о 12 14 17 пп](https://user-images.githubusercontent.com/69896204/91560715-f3770b80-e942-11ea-8734-4b664090b0fd.png)

The same issue in private mode in Firefox with or without wallet login. The conference room is not available and has grey view:

![Знімок екрана 2020-08-28 о 3 45 07 пп](https://user-images.githubusercontent.com/69896204/91562315-afd1d100-e945-11ea-83f6-22d14ce185a1.png)

![Знімок екрана 2020-08-28 о 1 34 01 пп](https://user-images.githubusercontent.com/69896204/91561707-b7dd4100-e944-11ea-9d5f-aa4b91f134b3.png)

![Знімок екрана 2020-08-28 о 1 34 14 пп](https://user-images.githubusercontent.com/69896204/91561721-bc095e80-e944-11ea-93cd-0773069e3b29.png)

**Comment by venimus** [comment]
This is related to #211

**Comment by venimus** [comment]
related to #207

**Comment by Liubov-crypto** [comment]
The rooms and dashboard are available, but there were some issues when joining the meeting in the Brave browser. I submitted the report via SH iframe wallet:
![Знімок екрана 2020-08-31 о 5 47 43 пп](https://user-images.githubusercontent.com/69896204/91733649-823d8f80-ebb2-11ea-85c5-37af0dbe80ee.png)
