### ISSUE TITLE
Tip button

### ISSUE THREAD

**Issue by mradkov** [aeternity/jitsi-meet#21]
Just a though - we can probably implement some sort of `clap` button.

https://github.com/aeternity/jitsi-meet/issues/21#issuecomment-638764765

**Comment by DeeJayElly** [comment]
> Just a though - we can probably implement some sort of `clap` button.

What is the behavior of clap button. Can you explain a bit more? Is it like raise hand or ping @mradkov ?

**Comment by mradkov** [comment]
This could evolve to a button for tipping (via superhero wallet). Send appreciation directly to the user.

Which is something we should think of implementation-wise. As superhero currently allows tips to be sent to public URLs only.

We should make a decision whether we want to have such tips made within a call to be present in the superhero.com tip feed.
- if so the tip should be a contract call to the tipping contract. The contract itself will require some adjustments to allow tips to users via the contract.
- second option would be to be a simple `spendtx`. In this case we would not be able to display it in superhero feed as this wont be registered in the tip contract.

**Comment by shapkarin** [comment]
@mradkov I think it should be the tip button at first version.

**Comment by shapkarin** [comment]
@mradkov because if we make it as `clap` we need to make jitsi server understand that.

**Comment by mradkov** [comment]
First implementation would be to integrate https://github.com/aeternity/superhero-button

**Comment by shapkarin** [comment]
Look like it's just to pass the account number of the dominant speaker and that's it. Maybe also check if that speaker is authed with superhero and maybe something other. I will check that.

**Comment by mradkov** [comment]
> Look like it's just to pass the account number of the dominant speaker and that's it. Maybe also check if that speaker is authed with superhero and maybe something other. I will check that.

Yes exactly. But also maybe a new icon and style should be developed for the button to match the proposed designs.

**Comment by shapkarin** [comment]
@mradkov here is the basic functionality above. I will finish with that later.

**Comment by shapkarin** [comment]
I will try to keep my commits more atomic

**Comment by shapkarin** [comment]
@mradkov we need to test it to make sure that the first speaker can also have the tip. The second will totally have.

**Comment by shapkarin** [comment]
I tested it a little and looks like it works fine. Only need to add some checks and next test with +3 people and long session.

**Comment by shapkarin** [comment]
@mradkov Also you will not see this button if you have only one user in room.

**Comment by shapkarin** [comment]
@mradkov I mention about long session because I'm afraid that with current integration garbage collector can't handle with so many instances.
Also that's why I open this issue https://github.com/aeternity/superhero-button/issues/11 and I think that better is to create a superhero button react component.

**Comment by mradkov** [comment]
> @mradkov I mention about long session because I'm afraid that with current integration garbage collector can't handle with so many instances.
> Also that's why I open this issue [aeternity/superhero-button#11](https://github.com/aeternity/superhero-button/issues/11) and I think that better is to create a superhero button react component.

I think the superhero-button should be compatible to be integrated in react it is also published on npm here: https://www.npmjs.com/package/@aeternity/superhero-button

**Comment by shapkarin** [comment]
@mradkov It's already pretty compatible but it can be done better. to achieve that we just need to change the package API a little bit and export some functions. Or we can create a react component from scratch.

**Comment by shapkarin** [comment]
@mradkov I mean that we can use this package as a dependency for the react's one. Hope I got your thoughts in a right way.

**Comment by shapkarin** [comment]
if that would be possible I think to write the test to test that button. At least [compare the memory and CPU usage](https://docs.cypress.io/guides/references/troubleshooting.html#Log-memory-and-CPU-usage) and what unit is used as current speaker, maybe there some latency or even a lag because of memory.

**Comment by mradkov** [comment]
> if that would be possible I think to write the test to test that button. At least [compare the memory and CPU usage](https://docs.cypress.io/guides/references/troubleshooting.html#Log-memory-and-CPU-usage) and what unit is used as current speaker, maybe there some latency or even a lag because of memory.

Tipping can happen async, I dont think it will make much difference in memory and CPU usage.

**Comment by shapkarin** [comment]
@mradkov can all contributors start to collaborate with react version in the separate repo maybe? It would be nice to build it all together.

**Comment by shapkarin** [comment]
@mradkov we can try to use the current one version as well. It's fine. Just not so cool as reacts one can be.

**Comment by shapkarin** [comment]
@mradkov we also had conversations about that. https://github.com/aeternity/superhero-button/issues/11 
And I also agree that it can be done without explicit dependency. For example we can use react context to propagate the props to all childs and implement the something like templates or at least invert color https://github.com/aeternity/superhero-button/issues/7.

**Comment by DeeJayElly** [comment]
Tipping functionality has been implemented.
