### ISSUE TITLE
Problems with connection and with tipping

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/jitsi-meet#210]
Hello team!
During the test call, there were problems with connection and with tipping:
![Знімок екрана 2020-08-28 о 1 28 47 пп](https://user-images.githubusercontent.com/69896204/91564585-7ef39b00-e949-11ea-84da-a2de737b7919.png)

![Знімок екрана 2020-08-28 о 1 29 31 пп](https://user-images.githubusercontent.com/69896204/91564601-8450e580-e949-11ea-9546-d9113e2f083b.png)

I used Chrome, Firefox and Brave browsers.

**Comment by venimus** [comment]
This is a network issue with aeternity middleware
