### ISSUE TITLE
Invite link doesn't work correctly

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/jitsi-meet#211]
When I log into Jitsi Meet (I use the web wallet) invite link does not work correctly: https://wallet.superhero.com/sign-message?x-success=https%3A%2F%2Fmeet.aepps.com%2FGladDaysRemindOnce%3Fresult%3Dsuccess%26signature%3D%7Bsignature%7D&x-cancel=https%3A%2F%2Fmeet.aepps.com%2FGladDaysRemindOnce%3Faddress%3Dak_cEjh5on5RvoBw8zqCGS4VWeY2bmNYNPjn3SCZutYyVLWKf7X1&message=I%20would%20like%20to%20generate%20JWT%20token%20at%20Fri,%2028%20Aug%202020%2012%3A30%3A56%20GMT

![Знімок екрана 2020-08-28 о 1 16 35 пп](https://user-images.githubusercontent.com/69896204/91564843-eb6e9a00-e949-11ea-9939-5a67f60e5327.png)

**Comment by venimus** [comment]
related to #207

**Comment by Liubov-crypto** [comment]
Seems that invite link works correctly, but options tip user via a button on avatar/text message are not available (Tip button is invisible):
![Знімок екрана 2020-08-31 о 6 50 24 пп](https://user-images.githubusercontent.com/69896204/91740504-0d6f5300-ebbc-11ea-943b-9556e857ea6d.png)
