### ISSUE TITLE
Only ak and .chain usernames

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#220]
@mike-gusev-ae I think to open an issue about that to discuss.

As far as I can see, we can add such checks:
- `regexp.test(username)` regexp we already have in utils
- and next if we have such username so check if `state['features/aeternity'].hasWallet` is `true` or at least if `state['features/base/jwt'].jwt` present.

**Comment by mike-gusev-ae** [comment]
I'm not sure that we need it.
I wanted to implement it only because of chat (#213 ), but it should work well right now. We found good solution.
And in other cases, fake users wont have avatars. So, we can easily find a fake among them.

**Comment by shapkarin** [comment]
@mike-gusev-ae I suggest that It's good to avoid fake superhero accounts.

**Comment by mike-gusev-ae** [comment]
Yes, of course, it won't be superfluous for sure

**Comment by shapkarin** [comment]
> And in other cases, fake users wont have avatars. So, we can easily find a fake among them.

Not really all, users are able to set some from options.

**Comment by shapkarin** [comment]
Also I think that in future we need to block any kind of account options for the superhero JWT users. So if user use JWT in this case avatar change must be blocked. But it's about other thing.

**Comment by venimus** [comment]
> Also I think that in future we need to block any kind of account options for the superhero JWT users. So if user use JWT in this case avatar change must be blocked. But it's about other thing.

you can't change avatar if you have jwt, you can add gravatar email but it will be ignored in the frontend (it will be used in mobile app tough, as it does not support anything else)
