### ISSUE TITLE
Don't show login with Superhero for the jitsi iframe

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#223]
After this superhero release - https://github.com/aeternity/superhero-ui/releases/tag/v0.1.13 
If user don't use extension wallet detector still can find wallet in superhero (right sidebar) so we don't longer need button `login with Superhero`

**Comment by venimus** [comment]
Mobile browser do not have extension or iframe wallet, so the best is to show it only for these

**Comment by shapkarin** [comment]
@venimus thanks. Can I take this task?
