### ISSUE TITLE
Stop the animation in prejoin when user click on "Cancel" in the popup

### ISSUE THREAD

**Issue by venimus** [aeternity/jitsi-meet#225]
We need to stop the waiting animation and text and show a message "Login canceled. Please refresh the page to try again" when user clicks Cancel in the JWT popup

Same should also happen on error

**Comment by shapkarin** [comment]
@venimus 
> Same should also happen on error

What kind of error? I cover only JWT sign related errors. Can add more.

**Comment by shapkarin** [comment]
@venimus I think that to cover all possible errors is some separate task. I covered only errors related to sign.

**Comment by shapkarin** [comment]
closed because of https://github.com/aeternity/jitsi-meet/pull/230
