### ISSUE TITLE
Allow providing message for the tip

### ISSUE THREAD

**Issue by venimus** [aeternity/jitsi-meet#232]
Tips have price and message but the current implementation the message is auto-generated. We need to allow people to customize that message.

Add a second input prefilled with the current autogenerated message in the Tip popup.

i.e.
![image](https://user-images.githubusercontent.com/632282/92223150-b366da00-eea8-11ea-9d91-1af779808073.png)

**Comment by shapkarin** [comment]
@venimus added commit above, need to add styles, will continue after double popups issue.
