### ISSUE TITLE
UX / UI suggestion for "agree to the terms" button in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/jitsi-meet#241]
UX/UI proposal: I propose to make the field where the user agrees to the wallet terms more visible (highlight). Because it is hard to see this field against this background:

![Знімок екрана 2020-09-07 о 4 45 34 пп](https://user-images.githubusercontent.com/69896204/92394889-110a5900-f12b-11ea-9b4e-3ee29c450b71.png)

**Comment by venimus** [comment]
this is an issue with https://github.com/aeternity/superhero-wallet
can you please create one there
