### ISSUE TITLE
Recording unavailable

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/jitsi-meet#274]
Steps to reproduce the behaviour:

1. Go to https://superhero.com/league
2. Join the event
3. Click on the burger menu
4. Click on Start Recording button
5. Click on Start Recording on the pop-up
6. See an error:

![Знімок екрана 2020-11-02 о 6 24 46 пп](https://user-images.githubusercontent.com/69896204/97894270-fc1d0100-1d3a-11eb-886f-0ec78362efb2.png)

OS: Mac 10.15.7
Wallet: Superhero 5d91965 / v.0.3.3
superhero ui: b9a82bc / 0.2.1

**Comment by venimus** [comment]
This is because jibri was not started

**Comment by Liubov-crypto** [comment]
I have checked that the error is reproducible again on my side.
