### ISSUE TITLE
Live Streaming unavailable

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/jitsi-meet#275]
Steps to reproduce the behaviour:

1. Go to https://superhero.com/league
2. Join the event
3. Click on the burger menu
4. Click on Start Live stream
5. Paste Youtube live stream key and Click on Start Live stream on the pop-up
6. See an error:

![Знімок екрана 2020-11-02 о 6 44 59 пп](https://user-images.githubusercontent.com/69896204/97895630-b95c2880-1d3c-11eb-9bdb-ffbe227f4d5d.png)

OS: Mac 10.15.7
Wallet: Superhero 5d91965 / v.0.3.3
superhero ui: b9a82bc / 0.2.1

**Comment by venimus** [comment]
This is because jibri was not started

**Comment by Liubov-crypto** [comment]
I have checked that the error is reproducible again on my side.
