### ISSUE TITLE
Put `Login with web wallet` in menu

### ISSUE THREAD

**Issue by mradkov** [aeternity/jitsi-meet#44]
`Login with webwallet` button should be probably somewhere in the menu as well, as it dissapears when there are more than 1 participants. (meaning it is only shown if there is nobody else in the room besides you)

![656f21b4-60a7-41a4-8ee1-91e72b5a7b5d](https://user-images.githubusercontent.com/13139371/85720830-78526880-b6f9-11ea-804f-ec18044b0c2f.png)

**Comment by shapkarin** [comment]
@mradkov Thanks. I will place it there.
