### ISSUE TITLE
Pin participant does not propagate

### ISSUE THREAD

**Issue by mradkov** [aeternity/jitsi-meet#62]
Pinning participant should be propagating the pinned users to all other participants in the room.

Could be a bug, or can be a feature that should be additionally implemented if jitsi does not support it.

**Comment by shapkarin** [comment]
@DeeJayElly that's not solved? I guess @Chima1707 know what to do, he can use the same approach like at that PR https://github.com/aeternity/jitsi-meet/pull/143

**Comment by shapkarin** [comment]
I can collaborate too

**Comment by venimus** [comment]
I think pining currently work when "follow me feature" is enabled from the host (or moderator).

**Comment by shapkarin** [comment]
@DeeJayElly @mike-gusev-ae can you provide the branches for that issue?

**Comment by mradkov** [comment]
> I think pining currently work when "follow me feature" is enabled from the host (or moderator).

Is this available for testing or preview somewhere?

**Comment by venimus** [comment]
> Is this available for testing or preview somewhere?

yes on all instances. I mean it does not pin for everyone, but more like similar behavior workaround. If the host pins it for himself and check "follow me" in settings, users will see what he sees including who he pinned.
