### ISSUE TITLE
Large resolution issue with main screen

### ISSUE THREAD

**Issue by venimus** [aeternity/jitsi-meet#74]
![image](https://user-images.githubusercontent.com/632282/86975415-f47c8f80-c180-11ea-84b7-29ac883fa141.png)

**Comment by mike-gusev-ae** [comment]
small resolutions. Looks like a bug too
![Screen Shot 2020-07-10 at 08 59 38](https://user-images.githubusercontent.com/67146735/87121739-24fd2000-c28c-11ea-8719-0991e9629218.png)
