### ISSUE TITLE
Always hide UI controls for the Recorder

### ISSUE THREAD

**Issue by venimus** [aeternity/jitsi-meet#98]
Since the streaming and recording service joins the room as normal user via browser it also takes into account the specific UI configuration. In our case we require controls to be always visible and that makes the recorder also show the controls (buttons) when streaming to youtube.

**Comment by shapkarin** [comment]
It needs some changes at 
https://github.com/aeternity/jitsi-meet/blob/a88b4b8cd9bce657580b289dc3d48b734bfd6ff8/modules/UI/UI.js#L173-L182

**Comment by shapkarin** [comment]
https://recorder_hide_controls.test.league.aeternity.org/test?#config.prejoinPageEnabled=false&config.iAmRecorder=true
